[package]
name = "yaml-subset"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.5.1"
pest_derive = "2.5.1"
linked-hash-map = "0.5.3"

[dev-dependencies]
insta = "1.23.0"
