WHITESPACE = { " " }

key_items = _{ !("[" | "]" | "." | "|") ~ ANY }
pure_key = { key_items* }

field = { (!("=") ~ ANY)+ }
value = { (!("." | "|") ~ ANY)+ }
condition = { field ~ "=" ~ value }
key = { pure_key ~ ( "|" ~ condition )* }

index_number = { ASCII_DIGIT+ }
index_all = { "*" }
index = _{ "[" ~ (index_number | index_all) ~ "]" }

part = { ((".") ~ key) | index }
path = { key ~ part* }  
final_path = { path ~ EOI }
